# Generated by Django 5.2.8 on 2026-05-21 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('channel_type', models.CharField(choices=[('TEXT', 'Text'), ('AUDIO', 'Audio')], default='TEXT', max_length=5)),
                ('scope', models.CharField(choices=[('DM', 'Direct Message'), ('GROUP', 'Group Call')], default='DM', max_length=5)),
                ('is_private', models.BooleanField(default=True)),
                ('is_active_call', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
