# Generated by Django 5.1.5 on 2025-04-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('channel_type', models.CharField(choices=[('TEXT', 'Text'), ('AUDIO', 'Audio')], default='TEXT', max_length=5)),
                ('scope', models.CharField(choices=[('DM', 'Direct Message'), ('GROUP', 'Group Call')], default='DM', max_length=5)),
                ('is_private', models.BooleanField(default=True)),
                ('is_active_call', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
