# Generated by Django 5.2.8 on 2026-05-21 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_channels', '0001_initial'),
        ('app_servers', '0001_initial'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_channels', to='app_users.profile'),
        ),
        migrations.AddField(
            model_name='channel',
            name='participants',
            field=models.ManyToManyField(related_name='channels', to='app_users.profile'),
        ),
        migrations.AddField(
            model_name='channel',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='app_servers.server'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('server', 'channel_type', 'name')},
        ),
    ]
