# Generated by Django 5.1.2 on 2024-12-01 17:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_channels', '0002_initial'),
        ('app_messages', '0003_message_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DirectMessageChannel',
            new_name='Channels',
        ),
    ]
