# Generated by Django 5.1.2 on 2024-11-19 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_channels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessagechannel',
            name='members',
            field=models.ManyToManyField(related_name='dm_channels', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
