# Generated by Django 5.1.5 on 2025-04-21 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_servers', '0001_initial'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelink',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_users.profile'),
        ),
        migrations.AddField(
            model_name='member',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='app_users.profile'),
        ),
        migrations.AddField(
            model_name='server',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_servers', to='app_users.profile'),
        ),
        migrations.AddField(
            model_name='member',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app_servers.server'),
        ),
        migrations.AddField(
            model_name='invitelink',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='app_servers.server'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('profile', 'server')},
        ),
    ]
