# Generated by Django 5.1.5 on 2025-04-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='servers/'),
        ),
        migrations.AddField(
            model_name='server',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
