# Generated by Django 5.1.5 on 2025-04-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servers', '0003_server_avatar_server_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='servers/avatars/'),
        ),
    ]
