# Generated by Django 5.1.2 on 2024-11-22 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_channels', '0002_initial'),
        ('app_messages', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app_channels.directmessagechannel'),
        ),
    ]
